sudo: required
matrix:
  include:
  - name: "Go 1.11"
    env: TEST_TARGET=shinobi
services:
  - docker
before_install:
  - docker-compose build
  - docker-compose up -d
install:
before_script:
  - docker-compose exec shinobi make depend
script:
  - docker-compose exec shinobi make test
after_script:
notifications:
